package v1

import "k8s.io/apimachinery/pkg/runtime"

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NumaTopology) DeepCopyInto(out *NumaTopology) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NumaTopology.
func (in *NumaTopology) DeepCopy() *NumaTopology {
	if in == nil {
		return nil
	}
	out := new(NumaTopology)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NumaTopology) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *NumaTopologySpec) DeepCopyInto(out *NumaTopologySpec) {
	*out = *in
	if in.NumaNodes != nil {
		in, out := &in.NumaNodes, &out.NumaNodes
		*out = make([]NumaNode, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *NumaNode) DeepCopyInto(out *NumaNode) {
	*out = *in
	if in.CPUs != nil {
		in, out := &in.CPUs, &out.CPUs
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
}

func (in *NumaTopologyList) DeepCopyInto(out *NumaTopologyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NumaTopology, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *NumaTopologyList) DeepCopy() *NumaTopologyList {
	if in == nil {
		return nil
	}
	out := new(NumaTopologyList)
	in.DeepCopyInto(out)
	return out
}

func (in *NumaTopologyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
